#create index
#PUT:metadata_name/:{"settings":{"analysis":{"analyzer":{"lowercasespaceanalyzer":{"type":"custom","tokenizer":"whitespace","filter":["lowercase"]}}},"index":{"number_of_shards":1,"number_of_replicas":1}},
#"mappings":{"default":{ "properties":{ "dbid":{"type":"text"}, "type":{"type":"text"}, "code":{"type":"text"}, "name":{"type":"text", "analyzer": "lowercasespaceanalyzer"}, "nameRaw":{"type":"text", "index" : false}}}}}

#create mapping
PUT:jam.cds/:{ "mappings":{"default":{ "properties":{ "dbid":{"type":"text"}, "type":{"type":"text"}, "id":{"type":"text", "index": false}, "name":{"type":"object", "enabled" : false}}}}}


