//package com.pac.msm.component.config;
//
//import com.pac.msm.Application;
//
//import org.slf4j.Logger;
//import org.slf4j.LoggerFactory;
//import org.springframework.boot.context.event.ApplicationReadyEvent;
//import org.springframework.context.ApplicationListener;
//import org.springframework.stereotype.Component;
//
//import java.io.InputStream;
//import java.util.Properties;
//
///**
// * This class is used to execute any custom code that should be
// * part of the startup process.
// */
//@Component
//public class ApplicationStartup implements ApplicationListener<ApplicationReadyEvent> {
//
//    public static String gitCommitId;
//
//    private static final Logger logger = LoggerFactory.getLogger(ApplicationStartup.class);
//
//    @Override
//    public void onApplicationEvent(final ApplicationReadyEvent event) {
//        loadGitInfo();
//    }
//
//    private static void loadGitInfo() {
//        try {
//            InputStream gitPropertiesFileStream = Application.class.getClassLoader().getResourceAsStream("git.properties");
//            if (gitPropertiesFileStream == null) {
//                logger.warn("Could not load git commit info since git.properties file is missing. This is likely due to " +
//                        "the file not being generated by the Maven build. As a result, no git information will be returned " +
//                        "when calling the /system/info API endpoint.");
//                return;
//            }
//
//            Properties properties = new Properties();
//            properties.load(gitPropertiesFileStream);
//            gitCommitId = properties.getProperty("git.commit.id");
//        } catch (Exception e) {
//            logger.warn("Could not load git.properties file due to exception: {}: {}", e.getClass().getSimpleName(), e.getMessage());
//        }
//    }
//
//}
